[package]
name = "ziggurat"
version = "0.1.0"
authors = ["Niklas <niklas@long.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
byteorder = "1"
chrono = "0.4"
sha2 = "0.9.3"

[dependencies.tokio]
version = "1"
features = [ "rt", "macros" ]
