[node]
kind = "zebra"
path = "/Users/nkls/dev/eqlabs/zebra"
start_command = "cargo +stable r -- --config node.toml --verbose start"

# Dockerized zcashd:

# local_ip = "0.0.0.0"

# [node]
# kind = "zcashd"
# path = "/Users/nkls"
# start_command = "docker start my_zcashd"
# stop_command = "docker stop my_zcashd"
# local_addr = "0.0.0.0:8080"
# external_addr = "0.0.0.0:8080"
# peer_ip = "host.docker.internal"

