on:
  workflow_call:

jobs:
  build-zcashd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: zcash/zcash
      - name: Build zcashd
        run: ./zcutil/build.sh -j$(nproc)
      - uses: actions/upload-artifact@v3
        with:
          name: zcashd-fetch-params
          path: ./zcutil/fetch-params.sh
      - uses: actions/upload-artifact@v3
        with:
          name: node-executable
          path: ./src/zcashd
